{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 142, \"exception_value\": \"TypeError('<models.hps.u_user.User object at 0x7f7c94753ad0> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 142, "exception_value": "TypeError('<models.hps.u_user.User object at 0x7f7c94753ad0> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-02T16:19:48", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:25:06", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'User' object has no attribute 'usercode'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'User' object has no attribute 'usercode'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-02T16:25:43", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:27:36", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:28:14", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:28:41", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:28:58", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError('<models.hps.u_user.User object at 0x7fc2b4f7ead0> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError('<models.hps.u_user.User object at 0x7fc2b4f7ead0> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-02T16:46:31", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError('<models.hps.u_user.User object at 0x7fef2dbb5ad0> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError('<models.hps.u_user.User object at 0x7fef2dbb5ad0> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-02T16:46:49", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:47:58", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-02T16:49:00", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError('<models.hps.u_user.User object at 0x7f07ab211ad0> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError('<models.hps.u_user.User object at 0x7f07ab211ad0> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-02T16:55:21", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError('<models.hps.u_user.User object at 0x7f16cfdd7ad0> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError('<models.hps.u_user.User object at 0x7f16cfdd7ad0> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-02T16:56:34", "remark": ""}
{"exception": ["{\"function\": \"__call__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 275, \"exception_value\": \"InvalidRequestError('When initializing mapper Mapper|Hotel|h_hotel, expression \\\\'h_checkin\\\\' failed to locate a name (\\\"name \\\\'h_checkin\\\\' is not defined\\\"). If this is a class name, consider adding this relationship() to the <class \\\\'models.hps.h_hotel.Hotel\\\\'> class after both dependent classes have been defined.',)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py\"}", {"function": "__call__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 275, "exception_value": "InvalidRequestError('When initializing mapper Mapper|Hotel|h_hotel, expression \\'h_checkin\\' failed to locate a name (\"name \\'h_checkin\\' is not defined\"). If this is a class name, consider adding this relationship() to the <class \\'models.hps.h_hotel.Hotel\\'> class after both dependent classes have been defined.',)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py"}], "log_time": "2019-01-07T09:46:30", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 31, \"exception_value\": \"AttributeError(\\\"'Query' object has no attribute 'like'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 31, "exception_value": "AttributeError(\"'Query' object has no attribute 'like'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T11:26:27", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 38, \"exception_value\": \"AttributeError(\\\"'Query' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 38, "exception_value": "AttributeError(\"'Query' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T11:27:06", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 38, \"exception_value\": \"AttributeError(\\\"'Query' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 38, "exception_value": "AttributeError(\"'Query' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T11:51:15", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 32, \"exception_value\": \"AttributeError(\\\"'Connection' object has no attribute 'excute'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/libs/orm/dbcontext.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 32, "exception_value": "AttributeError(\"'Connection' object has no attribute 'excute'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/libs/orm/dbcontext.py"}], "log_time": "2019-01-07T13:20:24", "remark": ""}
{"exception": ["{\"function\": \"construct_params\", \"exception_type\": \"<class 'sqlalchemy.exc.StatementError'>\", \"lineno\": 469, \"exception_value\": \"StatementError(\\\"A value is required for bind parameter 'UserCode' (original cause: InvalidRequestError: A value is required for bind parameter 'UserCode')\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py\"}", {"function": "construct_params", "exception_type": "<class 'sqlalchemy.exc.StatementError'>", "lineno": 469, "exception_value": "StatementError(\"A value is required for bind parameter 'UserCode' (original cause: InvalidRequestError: A value is required for bind parameter 'UserCode')\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py"}], "log_time": "2019-01-07T13:20:44", "remark": ""}
{"exception": ["{\"function\": \"_execute_clauseelement\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 790, \"exception_value\": \"AttributeError(\\\"'tuple' object has no attribute 'keys'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py\"}", {"function": "_execute_clauseelement", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 790, "exception_value": "AttributeError(\"'tuple' object has no attribute 'keys'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py"}], "log_time": "2019-01-07T13:22:25", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 49, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 49, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T13:23:28", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 49, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 49, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T13:24:53", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 49, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 49, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T13:28:55", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 50, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'UserID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 50, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'UserID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T13:31:12", "remark": ""}
{"exception": ["{\"function\": \"login\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 51, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'Tel'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/User/Login.py\"}", {"function": "login", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 51, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'Tel'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/User/Login.py"}], "log_time": "2019-01-07T13:31:36", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 41, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'has_key'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 41, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'has_key'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T14:45:24", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 41, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'has_key'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 41, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'has_key'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T14:47:18", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 41, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'has_key'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 41, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'has_key'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T14:47:56", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 41, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'has_key'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 41, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'has_key'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T14:49:53", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 41, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'has_key'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 41, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'has_key'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T14:50:56", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 47, \"exception_value\": \"KeyError('sSearchUserIDMust',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 47, "exception_value": "KeyError('sSearchUserIDMust',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:05:39", "remark": ""}
{"exception": ["{\"function\": \"data_handle\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 47, \"exception_value\": \"KeyError('sSearchUserIDMust',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "data_handle", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 47, "exception_value": "KeyError('sSearchUserIDMust',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:06:16", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 68, \"exception_value\": \"AttributeError(\\\"'dict' object has no attribute 'sHotelName'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 68, "exception_value": "AttributeError(\"'dict' object has no attribute 'sHotelName'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:06:25", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 68, \"exception_value\": \"AttributeError(\\\"'dict' object has no attribute 'sHotelNameLike'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 68, "exception_value": "AttributeError(\"'dict' object has no attribute 'sHotelNameLike'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:07:22", "remark": ""}
{"exception": ["{\"function\": \"construct_params\", \"exception_type\": \"<class 'sqlalchemy.exc.StatementError'>\", \"lineno\": 453, \"exception_value\": \"StatementError(\\\"A value is required for bind parameter 'DistrictID' (original cause: InvalidRequestError: A value is required for bind parameter 'DistrictID')\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py\"}", {"function": "construct_params", "exception_type": "<class 'sqlalchemy.exc.StatementError'>", "lineno": 453, "exception_value": "StatementError(\"A value is required for bind parameter 'DistrictID' (original cause: InvalidRequestError: A value is required for bind parameter 'DistrictID')\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py"}], "log_time": "2019-01-07T16:08:07", "remark": ""}
{"exception": ["{\"function\": \"construct_params\", \"exception_type\": \"<class 'sqlalchemy.exc.StatementError'>\", \"lineno\": 453, \"exception_value\": \"StatementError(\\\"A value is required for bind parameter 'DistrictID' (original cause: InvalidRequestError: A value is required for bind parameter 'DistrictID')\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py\"}", {"function": "construct_params", "exception_type": "<class 'sqlalchemy.exc.StatementError'>", "lineno": 453, "exception_value": "StatementError(\"A value is required for bind parameter 'DistrictID' (original cause: InvalidRequestError: A value is required for bind parameter 'DistrictID')\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py"}], "log_time": "2019-01-07T16:08:47", "remark": ""}
{"exception": ["{\"function\": \"construct_params\", \"exception_type\": \"<class 'sqlalchemy.exc.StatementError'>\", \"lineno\": 453, \"exception_value\": \"StatementError(\\\"A value is required for bind parameter 'ProviceID' (original cause: InvalidRequestError: A value is required for bind parameter 'ProviceID')\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py\"}", {"function": "construct_params", "exception_type": "<class 'sqlalchemy.exc.StatementError'>", "lineno": 453, "exception_value": "StatementError(\"A value is required for bind parameter 'ProviceID' (original cause: InvalidRequestError: A value is required for bind parameter 'ProviceID')\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py"}], "log_time": "2019-01-07T16:11:37", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 69, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 69, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:12:32", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 69, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 69, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T16:12:37", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(3L, None, u'\\\\\\\\u4e07\\\\\\\\u8c6a', u'\\\\\\\\u4e0a\\\\\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(3L, None, u'\\\\u4e07\\\\u8c6a', u'\\\\u4e0a\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:45:01", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(3L, None, u'\\\\\\\\u4e07\\\\\\\\u8c6a', u'\\\\\\\\u4e0a\\\\\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(3L, None, u'\\\\u4e07\\\\u8c6a', u'\\\\u4e0a\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:45:54", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(3L, None, u'\\\\\\\\u4e07\\\\\\\\u8c6a', u'\\\\\\\\u4e0a\\\\\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(3L, None, u'\\\\u4e07\\\\u8c6a', u'\\\\u4e0a\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:46:11", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(3L, None, u'\\\\\\\\u4e07\\\\\\\\u8c6a', u'\\\\\\\\u4e0a\\\\\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(3L, None, u'\\\\u4e07\\\\u8c6a', u'\\\\u4e0a\\\\u6d77', None, None, None, None, None, 1L, None, 1L, None, 1L, None, None, 1L, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5L, 3L, None, None, None, None, None, None, None, None, None, None, None, None, None) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:47:45", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(u'\\\\\\\\u4e07\\\\\\\\u8c6a', 1L, 1L, 1L) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(u'\\\\u4e07\\\\u8c6a', 1L, 1L, 1L) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:50:26", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 154, \"exception_value\": \"TypeError(\\\"(u'\\\\\\\\u4e07\\\\\\\\u8c6a', 1L, 1L, 1L) is not JSON serializable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 154, "exception_value": "TypeError(\"(u'\\\\u4e07\\\\u8c6a', 1L, 1L, 1L) is not JSON serializable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T16:51:29", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 69, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 69, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:28:22", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 74, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 74, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:35:02", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 76, \"exception_value\": \"TypeError(\\\"and_() got an unexpected keyword argument 'ProvinceID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 76, "exception_value": "TypeError(\"and_() got an unexpected keyword argument 'ProvinceID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:35:10", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 76, \"exception_value\": \"TypeError(\\\"and_() got an unexpected keyword argument 'ProvinceID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 76, "exception_value": "TypeError(\"and_() got an unexpected keyword argument 'ProvinceID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:35:27", "remark": ""}
{"exception": ["{\"function\": \"__bool__\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 495, \"exception_value\": \"TypeError(u'Boolean value of this clause is not defined',)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py\"}", {"function": "__bool__", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 495, "exception_value": "TypeError(u'Boolean value of this clause is not defined',)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py"}], "log_time": "2019-01-07T17:44:21", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 75, \"exception_value\": \"TypeError('like() takes at most 3 arguments (5 given)',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 75, "exception_value": "TypeError('like() takes at most 3 arguments (5 given)',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:46:22", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 72, \"exception_value\": \"TypeError(\\\"'Query' object is not callable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 72, "exception_value": "TypeError(\"'Query' object is not callable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:48:23", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 74, \"exception_value\": \"TypeError(\\\"'Query' object is not callable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 74, "exception_value": "TypeError(\"'Query' object is not callable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T17:59:43", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 74, \"exception_value\": \"TypeError(\\\"'Query' object is not callable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 74, "exception_value": "TypeError(\"'Query' object is not callable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:00:06", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 75, \"exception_value\": \"KeyError('nProvince',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 75, "exception_value": "KeyError('nProvince',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:00:22", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 75, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 75, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:01:00", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 88, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_start' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 88, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_start' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:36:49", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 88, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_start' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 88, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_start' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:37:49", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 91, \"exception_value\": \"AttributeError(\\\"'list' object has no attribute 'HotelID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 91, "exception_value": "AttributeError(\"'list' object has no attribute 'HotelID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:40:50", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 88, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_start' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 88, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_start' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:43:33", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 83, \"exception_value\": \"AttributeError(\\\"'module' object has no attribute 'strptime'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 83, "exception_value": "AttributeError(\"'module' object has no attribute 'strptime'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:47:57", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 83, \"exception_value\": \"AttributeError(\\\"'module' object has no attribute 'struct_time'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 83, "exception_value": "AttributeError(\"'module' object has no attribute 'struct_time'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:49:22", "remark": ""}
{"exception": ["{\"function\": \"to_datetime\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 415, \"exception_value\": \"TypeError('must be string, not datetime.datetime',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "to_datetime", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 415, "exception_value": "TypeError('must be string, not datetime.datetime',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T18:52:51", "remark": ""}
{"exception": ["{\"function\": \"_strptime\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 325, \"exception_value\": \"ValueError(\\\"time data '2014-01-01' does not match format '%Y-%m-%d %H:%M:%S'\\\",)\", \"filename\": \"/usr/lib64/python2.7/_strptime.py\"}", {"function": "_strptime", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 325, "exception_value": "ValueError(\"time data '2014-01-01' does not match format '%Y-%m-%d %H:%M:%S'\",)", "filename": "/usr/lib64/python2.7/_strptime.py"}], "log_time": "2019-01-07T18:53:57", "remark": ""}
{"exception": ["{\"function\": \"to_datetime\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 415, \"exception_value\": \"TypeError('must be string, not datetime.datetime',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "to_datetime", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 415, "exception_value": "TypeError('must be string, not datetime.datetime',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-07T18:55:41", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 91, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_end' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 91, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_end' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T18:59:32", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 91, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_end' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 91, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_end' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T19:01:37", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 91, \"exception_value\": \"UnboundLocalError(\\\"local variable 'checkin_datetime_end' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 91, "exception_value": "UnboundLocalError(\"local variable 'checkin_datetime_end' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T19:02:04", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 89, \"exception_value\": \"KeyError('sCheckInDateTimeEnd',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 89, "exception_value": "KeyError('sCheckInDateTimeEnd',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T19:02:57", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 89, \"exception_value\": \"KeyError('sCheckInDateTimeEnd',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 89, "exception_value": "KeyError('sCheckInDateTimeEnd',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T19:03:07", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 76, \"exception_value\": \"AttributeError(\\\"'RelationCheckIn' object has no attribute 'filter'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 76, "exception_value": "AttributeError(\"'RelationCheckIn' object has no attribute 'filter'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-07T19:39:09", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1054, \\\"Unknown column \\\\'h_relation_checkin.GuestState\\\\' in \\\\'field list\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1054, \"Unknown column \\'h_relation_checkin.GuestState\\' in \\'field list\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-07T19:39:39", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1054, \\\"Unknown column \\\\'h_relation_checkin.GuestState\\\\' in \\\\'field list\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1054, \"Unknown column \\'h_relation_checkin.GuestState\\' in \\'field list\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-07T19:42:57", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:34:42", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'\\\\' at line 4\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'\\' at line 4\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:35:22", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1051, \\\"Unknown table \\\\'g_guest_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1051, \"Unknown table \\'g_guest_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:35:45", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1054, \\\"Unknown column \\\\'h_hote.HotelID\\\\' in \\\\'on clause\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1054, \"Unknown column \\'h_hote.HotelID\\' in \\'on clause\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:36:20", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 61, \"exception_value\": \"AttributeError(\\\"'ResultProxy' object has no attribute 'all'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 61, "exception_value": "AttributeError(\"'ResultProxy' object has no attribute 'all'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T08:36:46", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_relation_checkin \\\\\\\\n                        Inner Join h_checkin On h_relation_c\\\\' at line 5\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_relation_checkin \\\\n                        Inner Join h_checkin On h_relation_c\\' at line 5\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:37:34", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'Inner Join g_guest_checkin On h_relation_checkin.HotelGuestID = g_guest_checkin.\\\\' at line 6\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'Inner Join g_guest_checkin On h_relation_checkin.HotelGuestID = g_guest_checkin.\\' at line 6\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:38:27", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:40:08", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:40:42", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_relation_checkin \\\\\\\\n                        Inner Join h_checkin On h_relation_c\\\\' at line 7\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_relation_checkin \\\\n                        Inner Join h_checkin On h_relation_c\\' at line 7\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:42:42", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:42:55", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_relation_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_relation_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:44:47", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:45:07", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:47:22", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:49:06", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_checkin \\\\\\\\n                        Inner Join h_hotel On h_checkin.HotelID = h_h\\\\' at line 10\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_checkin \\\\n                        Inner Join h_hotel On h_checkin.HotelID = h_h\\' at line 10\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:50:31", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:50:51", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1066, \\\"Not unique table/alias: \\\\'h_checkin\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1066, \"Not unique table/alias: \\'h_checkin\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:51:53", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:53:45", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1054, \\\"Unknown column \\\\'h_relation_checkin.HotelGuestID\\\\' in \\\\'on clause\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1054, \"Unknown column \\'h_relation_checkin.HotelGuestID\\' in \\'on clause\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T08:55:17", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:55:55", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:56:55", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'CheckInID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T08:57:12", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1052, \\\"Column \\\\'GuestDocID\\\\' in where clause is ambiguous\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1052, \"Column \\'GuestDocID\\' in where clause is ambiguous\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T09:00:18", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 70, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 70, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:08:19", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 70, \"exception_value\": \"KeyError('nProvinceID',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 70, "exception_value": "KeyError('nProvinceID',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:14:51", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 70, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 70, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:17:00", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 70, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 70, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:17:51", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 67, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 67, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:18:13", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'WhereAnd HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 13\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'WhereAnd HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 13\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T11:19:23", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'WhereHotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 13\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'WhereHotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 13\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T11:20:25", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 78, \"exception_value\": \"UnboundLocalError(\\\"local variable 'CityID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 78, "exception_value": "UnboundLocalError(\"local variable 'CityID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:26:24", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 77, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 77, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:27:44", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 78, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 78, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:36:26", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 78, \"exception_value\": \"UnboundLocalError(\\\"local variable 'ProvinceID' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 78, "exception_value": "UnboundLocalError(\"local variable 'ProvinceID' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:40:43", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 85, \"exception_value\": \"TypeError('get_data_from_sql() takes at least 4 arguments (3 given)',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 85, "exception_value": "TypeError('get_data_from_sql() takes at least 4 arguments (3 given)',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T11:56:07", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T11:56:35", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 43, \"exception_value\": \"KeyError('nPageSize',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 43, "exception_value": "KeyError('nPageSize',)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T13:19:11", "remark": ""}
{"exception": ["{\"function\": \"get_data_from_sql\", \"exception_type\": \"<type 'exceptions.KeyError'>\", \"lineno\": 182, \"exception_value\": \"KeyError('nPageNo',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/libs/orm/ormutils.py\"}", {"function": "get_data_from_sql", "exception_type": "<type 'exceptions.KeyError'>", "lineno": 182, "exception_value": "KeyError('nPageNo',)", "filename": "/home/devspace/public_cloud_pms/hps/src/libs/orm/ormutils.py"}], "log_time": "2019-01-08T13:19:45", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Limit 0, 1\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Limit 0, 1\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:20:08", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 43, \"exception_value\": \"TypeError(\\\"'NoneType' object has no attribute '__getitem__'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 43, "exception_value": "TypeError(\"'NoneType' object has no attribute '__getitem__'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T13:22:09", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 43, \"exception_value\": \"TypeError(\\\"'NoneType' object has no attribute '__getitem__'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 43, "exception_value": "TypeError(\"'NoneType' object has no attribute '__getitem__'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T13:22:15", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:23:17", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:25:48", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:26:01", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:27:55", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_hotel.HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\' Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_hotel.HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\' Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:31:00", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:31:55", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:32:57", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:33:25", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:34:00", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:37:39", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:37:44", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:42:29", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:42:50", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:43:11", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:43:31", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:43:49", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:44:15", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:45:08", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:45:33", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:46:12", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_hotel.HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'  Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_hotel.HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'  Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:48:11", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_hotel.HotelName Like \\\\'name\\\\'  Where HotelName Like \\\\'name\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_hotel.HotelName Like \\'name\\'  Where HotelName Like \\'name\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:51:08", "remark": ""}
{"exception": ["{\"function\": \"raw_decode\", \"exception_type\": \"<type 'exceptions.ValueError'>\", \"lineno\": 384, \"exception_value\": \"ValueError('No JSON object could be decoded',)\", \"filename\": \"/usr/lib64/python2.7/json/decoder.py\"}", {"function": "raw_decode", "exception_type": "<type 'exceptions.ValueError'>", "lineno": 384, "exception_value": "ValueError('No JSON object could be decoded',)", "filename": "/usr/lib64/python2.7/json/decoder.py"}], "log_time": "2019-01-08T13:51:20", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_hotel.HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'  Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_hotel.HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'  Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:51:31", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'h_hotel.HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'  Where HotelName Like \\\\'\\\\\\\\xe4\\\\\\\\xb8\\\\\\\\x87\\\\\\\\xe8\\\\\\\\xb1\\\\\\\\xaa\\\\'\\\\' at line 14\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'h_hotel.HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'  Where HotelName Like \\'\\\\xe4\\\\xb8\\\\x87\\\\xe8\\\\xb1\\\\xaa\\'\\' at line 14\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T13:52:06", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 135, \"exception_value\": \"UnboundLocalError(\\\"local variable 'CheckInDateTimeEnd' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 135, "exception_value": "UnboundLocalError(\"local variable 'CheckInDateTimeEnd' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T14:37:39", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.UnboundLocalError'>\", \"lineno\": 135, \"exception_value\": \"UnboundLocalError(\\\"local variable 'CheckInDateTimeEnd' referenced before assignment\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.UnboundLocalError'>", "lineno": 135, "exception_value": "UnboundLocalError(\"local variable 'CheckInDateTimeEnd' referenced before assignment\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T14:39:45", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1054, \\\"Unknown column \\\\'CheckInDate\\\\' in \\\\'where clause\\\\'\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1054, \"Unknown column \\'CheckInDate\\' in \\'where clause\\'\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T14:49:13", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.OperationalError'>\", \"lineno\": 36, \"exception_value\": \"OperationalError('(OperationalError) (1052, \\\"Column \\\\'CheckInTime\\\\' in where clause is ambiguous\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.OperationalError'>", "lineno": 36, "exception_value": "OperationalError('(OperationalError) (1052, \"Column \\'CheckInTime\\' in where clause is ambiguous\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T14:49:56", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 165, \"exception_value\": \"TypeError(\\\"unsupported operand type(s) for %: 'TextClause' and 'str'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 165, "exception_value": "TypeError(\"unsupported operand type(s) for %: 'TextClause' and 'str'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T15:12:10", "remark": ""}
{"exception": ["{\"function\": \"search_all_checkin\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 165, \"exception_value\": \"TypeError(\\\"unsupported operand type(s) for %: 'TextClause' and 'str'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py\"}", {"function": "search_all_checkin", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 165, "exception_value": "TypeError(\"unsupported operand type(s) for %: 'TextClause' and 'str'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/SearchAllCheckInList.py"}], "log_time": "2019-01-08T15:12:36", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'From\\\\\\\\n                        h_relation_checkin \\\\\\\\n                        Inner J\\\\' at line 4\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'From\\\\n                        h_relation_checkin \\\\n                        Inner J\\' at line 4\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T15:13:41", "remark": ""}
{"exception": ["{\"function\": \"__getitem__\", \"exception_type\": \"<class 'sqlalchemy.exc.InvalidRequestError'>\", \"lineno\": 88, \"exception_value\": \"InvalidRequestError(\\\"Ambiguous column name 'HotelGuestID' in result set! try 'use_labels' option on select statement.\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getitem__", "exception_type": "<class 'sqlalchemy.exc.InvalidRequestError'>", "lineno": 88, "exception_value": "InvalidRequestError(\"Ambiguous column name 'HotelGuestID' in result set! try 'use_labels' option on select statement.\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T15:15:56", "remark": ""}
{"exception": ["{\"function\": \"defaulterrorhandler\", \"exception_type\": \"<class 'sqlalchemy.exc.ProgrammingError'>\", \"lineno\": 36, \"exception_value\": \"ProgrammingError('(ProgrammingError) (1064, \\\"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\\\'As obj, g_guest_checkin.*, g_guest_doc.*, g_foreigner.*\\\\\\\\n                    From\\\\' at line 3\\\")',)\", \"filename\": \"/usr/lib64/python2.7/site-packages/MySQLdb/connections.py\"}", {"function": "defaulterrorhandler", "exception_type": "<class 'sqlalchemy.exc.ProgrammingError'>", "lineno": 36, "exception_value": "ProgrammingError('(ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \\'As obj, g_guest_checkin.*, g_guest_doc.*, g_foreigner.*\\\\n                    From\\' at line 3\")',)", "filename": "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py"}], "log_time": "2019-01-08T15:19:26", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:26:49", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:32:27", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:36:34", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:37:23", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:38:28", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:38:40", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:39:17", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:41:15", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:41:56", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:44:36", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:45:28", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:46:23", "remark": ""}
{"exception": ["{\"function\": \"__getattr__\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 98, \"exception_value\": \"AttributeError(\\\"Could not locate column in row for column 'copy'\\\",)\", \"filename\": \"/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py\"}", {"function": "__getattr__", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 98, "exception_value": "AttributeError(\"Could not locate column in row for column 'copy'\",)", "filename": "/usr/lib/python2.7/site-packages/sqlalchemy/engine/result.py"}], "log_time": "2019-01-08T16:47:49", "remark": ""}
{"exception": ["{\"function\": \"wrapper\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 33, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'success'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py\"}", {"function": "wrapper", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 33, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'success'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/core/modules/module_handle.py"}], "log_time": "2019-01-09T11:09:57", "remark": ""}
{"exception": ["{\"function\": \"get_checkin_detail\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 30, \"exception_value\": \"AttributeError(\\\"'NoneType' object has no attribute 'CheckInID'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py\"}", {"function": "get_checkin_detail", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 30, "exception_value": "AttributeError(\"'NoneType' object has no attribute 'CheckInID'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py"}], "log_time": "2019-01-09T11:11:21", "remark": ""}
{"exception": ["{\"function\": \"get_checkin_detail\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 31, \"exception_value\": \"TypeError(\\\"'CheckIn' object is not iterable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py\"}", {"function": "get_checkin_detail", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 31, "exception_value": "TypeError(\"'CheckIn' object is not iterable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py"}], "log_time": "2019-01-09T11:16:43", "remark": ""}
{"exception": ["{\"function\": \"get_checkin_detail\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 31, \"exception_value\": \"TypeError(\\\"'CheckIn' object is not iterable\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py\"}", {"function": "get_checkin_detail", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 31, "exception_value": "TypeError(\"'CheckIn' object is not iterable\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py"}], "log_time": "2019-01-09T11:17:05", "remark": ""}
{"exception": ["{\"function\": \"json_default\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 169, \"exception_value\": \"TypeError('<models.hps.h_checkin.CheckIn object at 0x7f0fe9a5bc50> is not JSON serializable',)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/utils/tools.py\"}", {"function": "json_default", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 169, "exception_value": "TypeError('<models.hps.h_checkin.CheckIn object at 0x7f0fe9a5bc50> is not JSON serializable',)", "filename": "/home/devspace/public_cloud_pms/hps/src/utils/tools.py"}], "log_time": "2019-01-09T11:25:35", "remark": ""}
{"exception": ["{\"function\": \"get_checkin_detail\", \"exception_type\": \"<type 'exceptions.AttributeError'>\", \"lineno\": 31, \"exception_value\": \"AttributeError(\\\"'CheckIn' object has no attribute 'delattr'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py\"}", {"function": "get_checkin_detail", "exception_type": "<type 'exceptions.AttributeError'>", "lineno": 31, "exception_value": "AttributeError(\"'CheckIn' object has no attribute 'delattr'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py"}], "log_time": "2019-01-09T11:30:21", "remark": ""}
{"exception": ["{\"function\": \"get_checkin_detail\", \"exception_type\": \"<type 'exceptions.TypeError'>\", \"lineno\": 31, \"exception_value\": \"TypeError(\\\"attribute name must be string, not 'NoneType'\\\",)\", \"filename\": \"/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py\"}", {"function": "get_checkin_detail", "exception_type": "<type 'exceptions.TypeError'>", "lineno": 31, "exception_value": "TypeError(\"attribute name must be string, not 'NoneType'\",)", "filename": "/home/devspace/public_cloud_pms/hps/src/api/Guest/GetCheckinDetail.py"}], "log_time": "2019-01-09T11:32:35", "remark": ""}
